- pom.xml
https://github.com/googleapis/java-trace/issues/35 was made and released in the trace bom a while ago, so I expected `google-cloud-bom` to also pick it up by now, but it looks like it's still using an old trace bom. I somehow thought these updates are automatic, but I guess not. Is it ok to update the trace bom version to release that fix to `google-cloud-bom` users?
> fix: bump trace to fix missing dependency

- pom.xml
It seems renovate cannot find dependency upgrades for our `-alpha` or `-beta` versions.
> deps: update library versions

- renovate.json
This should fix the issue which prevented renovate from updating the version in #169 
If this works, we will update our common templates with this config.
Suggestion from: https://github.com/renovatebot/config-help/issues/490
> chore: allow renovate to update unstable google-cloud packages

- versions.txt
The next release version will be `0.123.0` rather than `0.123.0-alpha`
> chore: drop alpha version from release tag

- .github/release-please.yml
- synth.py
This should tell release-please to look at the dependencies being updated and bump the minor version of this artifact if any dependency bumped its minor version.
> chore: use bom versioning strategy for releases

- .kokoro/nightly/dashboard.cfg
- .kokoro/nightly/dashboard.sh
- dashboard/README.md
- dashboard/pom.xml
- dashboard/src/main/java/com/google/cloud/tools/opensource/cloudbomdashboard/ArtifactCache.java
- dashboard/src/main/java/com/google/cloud/tools/opensource/cloudbomdashboard/ArtifactInfo.java
- dashboard/src/main/java/com/google/cloud/tools/opensource/cloudbomdashboard/ArtifactResults.java
- dashboard/src/main/java/com/google/cloud/tools/opensource/cloudbomdashboard/DashboardArguments.java
- dashboard/src/main/java/com/google/cloud/tools/opensource/cloudbomdashboard/DashboardMain.java
- dashboard/src/main/resources/css/dashboard.css
- dashboard/src/main/resources/js/dashboard.js
- dashboard/src/main/resources/poms/demo.xml
- dashboard/src/main/resources/templates/index.ftl
- dashboard/src/main/resources/templates/macros.ftl
- dashboard/src/main/resources/templates/version_index.ftl
Overview:
We intend to use google-cloud-shared-dependencies for all the libraries in the google-cloud-bom. To avoid dependency conflict, we want to make sure the versions of google-cloud-shared-dependencies in all the libraries are the same before we actually release the bom.  So we try to build a dashboard for google-cloud-bom to show the version of google-cloud-shared-dependencies in the libraries of google-cloud-bom.
Goals:
1. Calculate the number of libraries in the google-cloud-bom and show them
2. Count the number of libraries where upper bounds errors occur
3. Count the number of libraries who fail to converge
4. Show the version of libraries in the bom and the latest version released in the Maven Center with release date.
5. Show the version of google-cloud-shared-dependencies in …
> feat: add dashboard for shared dependency version checking

- pom.xml
This is a private alpha client that is no longer updated. We will add google-cloud-game-servers (this artifact/service's successor) when it is 1.0.0
See #470
> deps!: remove google-cloud-gameservices from bom

- .github/auto-approve.yaml
> chore: auto-approve renovate PRs to update cloud client library artifacts

- .github/sync-repo-settings.yaml
See https://github.com/googleapis/repo-automation-bots/pull/754
Required status check configs can now be configured locally.
> chore: specify repo settings overrides in local configuration

- pom.xml
The API (alpha) was turned down.
> feat!: remove google-cloud-irm

- .github/sync-repo-settings.yaml
to stop the delay in merging many PRs
> chore: not to require up to date branches

- .github/sync-repo-settings.yaml
- .github/trusted-contribution.yml
- .github/workflows/bom-upper-bounds.yaml
- synth.py
This should allow us to stop requiring Kokoro at all - we don't actually have any integration tests to run here and the upper-bounds-check can happen on GitHub actions.
> build: run bom-upper-bounds check on GitHub actions

- dashboard/src/main/java/com/google/cloud/tools/opensource/cloudbomdashboard/DashboardMain.java
google-cloud-firestore-admin is a module in java-firestore repo
fixes #1150
> fix: dashboard exclude google-cloud-firestore-admin

- pom.xml
We're not ready to switch users to google-cloud-compute 1.0.0 (diregapic client).
> deps: update google-cloud-compute to 0.119.4-alpha

- dashboard/pom.xml
Add back some dependencies accidentally removed in #1665 for building the dashboard and the dashboard report.
> chore: add back needed dashboard dependencies

- .github/workflows/dashboard.yaml
- .kokoro/dashboard.sh
- dashboard/src/main/java/com/google/cloud/tools/opensource/cloudbomdashboard/DashboardArguments.java
- dashboard/src/main/java/com/google/cloud/tools/opensource/cloudbomdashboard/DashboardMain.java
> ci: add Github Actions workflow to check convergence in a release PR

- .github/sync-repo-settings.yaml
As per https://github.com/googleapis/java-cloud-bom/pull/1940#issuecomment-828558092, I'm deleting the upper-bounds check from this repository. This is the first step of removing the upper bounds check in this repository.
Once the "required" mark is gone, I'll delete the files in #1942.
> ci: removing upper bounds check from required checks

- dependency-convergence/pom.xml
- pom.xml
Added the following libraries:
- java-dms
- java-essential-contacts
- java-aiplatform
- java-gsuite-addons
- java-service-usage
- java-workflow-executions
- java-api-gateway
- java-shell
- java-tpu
- java-vpcaccess
> feat: add newly promoted libraries to google-cloud-bom

- pom.xml
Reverts googleapis/java-cloud-bom#3496
We should not include any new non-stable APIs in this BOM
> revert: "feat: add google-cloud-logging-servlet-initializer"

- dependency-convergence/pom.xml
```
[INFO] --- maven-enforcer-plugin:3.0.0:enforce (enforce) @ full-convergence-check ---
[WARNING] 
Dependency convergence error for com.google.api.grpc:proto-google-iam-v1:jar:1.2.6:compile paths to dependency are:
+-com.google.cloud:full-convergence-check:pom:0.170.1-SNAPSHOT
+-com.google.cloud:google-cloud-artifact-registry:jar:1.1.0:compile
+-com.google.api.grpc:proto-google-iam-v1:jar:1.2.6:compile
and
+-com.google.cloud:full-convergence-check:pom:0.170.1-SNAPSHOT
+-com.google.cloud:google-cloud-asset:jar:3.2.15:compile
+-com.google.api.grpc:proto-google-iam-v1:jar:1.2.6:compile
...
[WARNING] 
Dependency convergence error for org.checkerframework:checker-compat-qual:jar:2.5.5:compile paths to dependency are:
+-com.google.cloud:full-convergence-check:pom:0.170.1-SNAPSHOT …
```
> fix(test): excluding checker-compat-qual from full convergence test

- release-please-config.json
This enables the maven-workspace plugin so a release for google-cloud-bom will bump its version in libraries-bom
> build: try to enable maven-workspace plugin

- libraries-bom/pom.xml
- owlbot.py
- renovate.json
https://github.com/googleapis/java-shared-dependencies/blob/v2.12.0/first-party-dependencies/pom.xml
The Libraries BOM should not give the latest versions to our library users. Rather, it should give the versions in the corresponding shared dependencies BOM. The versions of the shared dependencies BOM 2.12.0 are the core library versions that we built and tested for the client libraries.
There's a planned enhancement for phase 2 where the Libraries BOM use the first-party-dependencies BOM (a part of the shared dependencies BOM).
> deps(libraries-bom): use library versions from the shared dependencies BOM 2.12.0

- .github/sync-repo-settings.yaml
- libraries-bom/pom.xml
- Making bom-content-test as required
- The Libraries BOM should use snapshot for bom-content-test
> ci: bom-content-test as required. libraries-bom to use snapshot

- release-please-config.json
As per @chingor13  and https://github.com/googleapis/release-please/blob/main/docs/manifest-releaser.md#configfile, the option is "bump-minor-pre-major".
Fixes https://github.com/googleapis/release-please/issues/1462
> ci: bump-minor-pre-major in the config file

- libraries-bom/pom.xml
- pom.xml
This is troubleshooting for failures in https://github.com/googleapis/java-cloud-bom/pull/4463 and fix.
- The release profile was missing in the libraries-bom/pom.xml, resulting in the error of *.asc file
- The root project needs to declare nexus-staging-plugin to run "mvn nexus-staging:release" command
- The root project itself is not to be released. So declaring the nexus-staging-plugin in a profile that is activated in "mvn nexus-staging:release".
> build: release profile in libraries-bom

- libraries-bom/pom.xml
Libraries BOM update with the shared dependencies BOM 2.13.0
https://github.com/googleapis/java-shared-dependencies/blob/v2.13.0/third-party-dependencies/pom.xml
https://search.maven.org/artifact/com.google.api/gax-bom/2.18.2/pom
has gax-httpjson 0.103.2.
> deps: libraries-bom update with shared dependencies BOM 2.13.0

- libraries-bom/pom.xml
- tests/dependency-convergence/pom.xml
google-cloud-dataproc had a major version bump (v4). This pull request bumps the libraries BOM version to accomodate the change. Until Release Please can take care of the major version bump via google-cloud-bom, we maintain the version manually.
tests/dependency-convergence/pom.xml needs to reference the next version to resolve the failing check https://github.com/googleapis/java-cloud-bom/pull/4502#issuecomment-1177547876
> feat!: preparing for next release

- tests/dependency-convergence/pom.xml
Using x-version-update-start tag in the tests module when referencing google-cloud-bom version.
> build: use x-version-update-start in tests module

- release-please-config.json
- tests/dependency-convergence/pom.xml
Release Please updates the versions listed in the manifest only (Related: https://github.com/googleapis/release-please/issues/1453). The tests module is not touched by Release Please. This pull request attempts to include the module into the scope of Release Please
Because of this gap, currently the tests/dependency-convergence module fails when we create a new version:
```
[INFO] Scanning for projects...
Error: ] Some problems were encountered while processing the POMs:
Error:  'dependencies.dependency.version' for com.google.cloud:google-cloud-datastream:jar is missing. @ line 146, column 18
Error:  'dependencies.dependency.version' for com.google.cloud:google-cloud-dataplex:jar is missing. @ line 150, column 18
Error:  'dependencies.dependency.version' for …
```
> build: Release Please to control tests module too

- libraries-bom/pom.xml
Setting versions for https://github.com/googleapis/java-shared-dependencies/blob/v3.0.1/third-party-dependencies/pom.xml.
From next release, the Libraries BOM start importing gax-bom. This will provide gax's testlib artifacts to users (https://github.com/googleapis/java-cloud-bom/issues/4694) as well as easing our maintenance of setting gax and gax-httpjson versions. With `mvn help:effective-pom`, I confirmed the GAX artifacts are available for BOM users:
```
suztomo@suztomo2:~/java-cloud-bom/libraries-bom$ mvn help:effective-pom |grep -A2 gax
<gax.version>2.18.7</gax.version>
<google.cloud.core.version>2.8.6</google.cloud.core.version>
<gson.version>2.9.1</gson.version>
--
<artifactId>gax</artifactId>
<version>2.18.7</version>
</dependency>
--
<artifactId>gax</artifactId> …
```
> deps: java-shared-dependencies 3.0.1 and using gax-bom

- .github/workflows/full-convergence-check.yaml
- tests/pom.xml
- tests/src/test/java/com/google/cloud/BomContentAssertionsTest.java
- tests/src/test/java/com/google/cloud/BomContentTest.java
The assertions on the dependency convergence among Cloud Java libraries:
```
Managed dependency com.google.cloud:google-cloud-bigquery:jar:2.13.8 has dependency com.google.cloud:google-cloud-bigquerystorage:jar:2.14.2, which should be 2.15.0 (the version in the BOM).
Managed dependency com.google.cloud:google-cloud-nio:jar:0.124.7 has dependency com.google.cloud:google-cloud-storage:jar:2.9.0, which should be 2.9.2 (the version in the BOM).
Managed dependency com.google.cloud:google-cloud-notification:jar:0.123.2-beta has dependency com.google.cloud:google-cloud-storage:jar:2.7.2, which should be 2.9.2 (the version in the BOM).
Managed dependency com.google.cloud:google-cloud-notification:jar:0.123.2-beta has dependency com.google.cloud:google-cloud-pubsub:jar:1.119.1, which should be …
```
> test: assert convergence among Cloud Java client libraries

- release-please-config.json
skip-github-release for the "tests/dependency-convergence" module.
Using https://github.com/googleapis/release-please/blob/main/docs/manifest-releaser.md#configfile:
```
"skip-github-release": {
"description": "Skip tagging GitHub releases for this package. Defaults to `false`.",
"type": "boolean"
},
```
> ci: skip-github-release for  the "tests/dependency-convergence" module

- libraries-bom/pom.xml
- renovate.json
With this pull request, we don't need to manually maintain the property values for the Google Core libraries.
Here is the comparison of the artifacts in before and after https://gist.github.com/suztomo/8da4e33c5ca501aae2d8fd645a7c305c (3 files). The diff of the two list shows that there's no artifacts removed by this change.
There are new additions because we start importing new BOMs, such as google-cloud-core-bom and grpc-bom. We used to declare some of the artifacts there independently, and thus other artifacts were not in the Libraries BOM. Now they're part of the Libraries BOM.
RenovateBot was turned off because latest versions are not guaranteed to be tested with Google Cloud client libraries. Now the versions in the first-party-dependencies are tested. We can rely on RenovateBot …
> deps: use first-party-dependencies in libraries-bom

- tests/src/test/java/com/google/cloud/BomContentTest.java
BOMContentTest is currently failing because a GWT class `com.google.gwt.core.client.UnsafeNativeLong` (https://github.com/googleapis/java-cloud-bom/pull/5124#issuecomment-1251057283) appears in multiple JAR files. Guava-GWT is added because we start using guava-bom in  #5125 . However GWT (the technology that works on browser) is not intended to communicate with Google Cloud through Cloud Java client library.
With this PR, the GWT classes (package "com.google.gwt") are excluded from the check.
> test: exclude UnsafeNativeLong for duplicate class

- google-cloud-bom/pom.xml
google-cloud-gapic-libraries BOM 0.2.0 provides the versions of
these artifacts.
https://search.maven.org/artifact/com.google.cloud/gapic-libraries-bom/0.2.0/pom
> deps: remove unnecesary artifacts in BOM

- tests/src/test/java/com/google/cloud/BomContentTest.java
> test: allowlist to include module-info

- README.md
With 26.1.5 BOM release, we include preview libraries in the Libraries BOM.
> With this release, we started including preview libraries to the BOM (version pre 1.0) into the Libraries BOM, so that Cloud customers can use both stable and preview Cloud Java libraries with consistent dependencies without dependency conflicts. For the distinction of stable and preview versions, please refer to https://github.com/googleapis/google-cloud-java/#versioning.
https://github.com/googleapis/java-cloud-bom/releases/tag/libraries-bom-v26.1.5
> docs: README to reflect the BOM includes preview libraries

- .github/workflows/full-convergence-check.yaml
Removing (failing) Linkage Check in favor of "shared-dependencies-convergence" check. As long as the client libraries use the shared dependencies and their tests pass, we won't encounter dependency conflicts.
Linkage Checker is known to report false positives such as https://github.com/googleapis/java-cloud-bom/issues/5161
Closes https://github.com/googleapis/java-cloud-bom/issues/5161
> ci: removing Linkage Check

- .github/workflows/release-note-generation.yaml
- ci: trigger on release
- released type
A test with my fork https://github.com/suztomo/java-cloud-bom didn't trigger the job somehow. Let's see the event in the original repository. If this does not work in next release, I'll seek a way to setup a job upon merging release please pull requests.
> ci: trigger release note creation on release

- .github/workflows/ci-release-note-generation.yaml
- .github/workflows/release-note-generation.yaml
- release-note-generation/pom.xml
- release-note-generation/src/main/java/com/google/cloud/ReleaseNoteGeneration.java
- release-note-generation/src/test/java/com/google/cloud/ReleaseNoteGenerationTest.java
The release notes of the Libraries BOM to have Cloud Java libraries' new feature and bug fixes highlighted.
Screenshot:
The changes in the google-cloud-java monorepo is not in this pull request.
> chore: release note to show notable changes

- .github/workflows/release-note-generation.yaml
Release note generation script failed for 26.3.0 release last week because it didn't handle the GITHUB_REF value properly:
This PR fixes it.
> fix: release note script to handle GITHUB_REF properly

- .github/release-please.yml
- .github/sync-repo-settings.yaml
> chore: preparing 26.1.x branch

- renovate.json
In this repository, renovate.json is excluded in owlbot.py.
As per discussion with @meltsufin , RenovateBot touching requirement.txt causes conflicts between RenovateBot and OwlBot Postprocessor. I'm excluding the file via renovate.json following what @mpeddada1 did in https://github.com/googleapis/synthtool/blob/master/synthtool/gcp/templates/java_library/renovate.json#L15
> chore: exclude requirement.txt in renovate.json

- google-cloud-bom/pom.xml
- libraries-bom/pom.xml
Overriding gax version to patched 2.19.6 in java-cloud-bom's 26.1.x branch.
> deps: overriding gax, protobuf, and bigquerystorage to patched versions

- .github/workflows/release-note-generation.yaml
With the single-component setup, the GITHUB_REF variable does not carry "libraries-bom-" in it. (In the previous release, the value was refs/tags/v) 26.5.0 release note generation job failed: https://github.com/googleapis/java-cloud-bom/actions/runs/4018419177/jobs/6904012339
```
+ '[' -n '' ']'
Couldn't find the Libraries BOM version. WORKFLOW_DISPATCH_INPUT       was empty and GITHUB_REF was refs/tags/v26.5.0.
+ [[ refs/tags/v26.5.0 == *\l\i\b\r\a\r\i\e\s\-\b\o\m* ]]
+ echo 'Couldn'\''t find the Libraries BOM version. WORKFLOW_DISPATCH_INPUT       was empty and GITHUB_REF was refs/tags/v26.5.0.'
+ exit 1
```
Therefore I'm adjusting the script to read the version in this pull request.
> ci: release note generation for single-component setup

- .github/workflows/release-note-generation.yaml
Previous attempt https://github.com/googleapis/java-cloud-bom/pull/5788 failed.
With single-component setup, the tag no longer carries "libraries-bom" prefix.
> ci: fixing update release tag in release-note job

- tests/src/test/java/com/google/cloud/BomContentTest.java
There's another check that verifies the existence of the BOM entries.
Without this workaround, the check fails in the release pull request: https://github.com/googleapis/java-cloud-bom/pull/5891#issuecomment-1496615657
> test: temporary fix for the BOM assertion logic

- libraries-bom/pom.xml
Follow-up to PR https://github.com/googleapis/java-cloud-bom/pull/6000. PR 6000 is only updating the shared-dependencies version to 3.10.0. The desired version is 3.10.1.
> deps: update dependency com.google.cloud:first-party-dependencies to v3.10.1

- google-cloud-bom/pom.xml
manual create for v2.22.5.
release cut to maintain dependency consistency ([context](https://github.com/googleapis/google-cloud-java/pull/9573#issuecomment-1602935279)).
> deps: update dependency com.google.cloud:google-cloud-storage-bom to v2.22.5

- .github/workflows/update-readme-table.yaml
Fixes error in indentation of update README table workflow. This fix should enable the workflow to be manually triggered.
> chore: update README table workflow to be able to be manually triggered

- .github/workflows/update-readme-table.yaml
Workflow failing due to missing `pyyaml` step: https://github.com/googleapis/java-cloud-bom/actions/runs/5647840842/job/15298785356
```
Traceback (most recent call last):
File "/home/runner/work/java-cloud-bom/java-cloud-bom/libraries-bom-table-generation/updateREADMETable.py", line 3, in <module>
import yaml
ModuleNotFoundError: No module named 'yaml'
```
This should fix that.
> chore: add pyyaml installation step to workflow

- .github/workflows/update-readme-table.yaml
Workflow failing: https://github.com/googleapis/java-cloud-bom/actions/runs/5648078883/job/15299506022 due to branch protection rules on `main`:
```
remote: error: GH006: Protected branch update failed for refs/heads/main.        
remote: error: Changes must be made through a pull request. 8 of 8 required status checks are expected.        
To https://github.com/googleapis/java-cloud-bom
! [remote rejected] main -> main (protected branch hook declined)
error: failed to push some refs to 'https://github.com/googleapis/java-cloud-bom'
```
This updates the workflow to push the PR from a separate branch.
> chore: update workflow to use branch instead of main

- .github/workflows/update-readme-table.yaml
Workflow currently generates PR without the correct prefix: https://github.com/googleapis/java-cloud-bom/pull/6115
It also uses the generic Github Actions Bot which does not pass the CLA check. Switching to use the Cloud Java bot
> chore: update workflow to generate PRs with correct commit prefix and use Cloud Java bot

- .github/workflows/update-readme-table.yaml
https://github.com/googleapis/java-cloud-bom/actions/runs/5659031293/job/15331677438
Workflow fails:
```
Switched to a new branch 'update-readme'
To https://github.com/googleapis/java-cloud-bom
! [rejected]        update-readme -> update-readme (fetch first)
error: failed to push some refs to 'https://github.com/googleapis/java-cloud-bom'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
```
This should clean it up by deleting the branch before re-creating it each time the README is updated.
> chore: update workflow to clean up branch

- .github/workflows/update-readme-table.yaml
Workflow failed: https://github.com/googleapis/java-cloud-bom/actions/runs/5659974377
```
Run gh pr create --base main --head update-readme --title "chore: Update README with release table" --body "Updating README with the table of artifacts associated with the latest libraries-bom release"
gh: To use GitHub CLI in a GitHub Actions workflow, set the GH_TOKEN environment variable. Example:
env:
GH_TOKEN: ${{ github.token }}
```
> chore: update workflow to use GH_TOKEN instead of GITHUB_TOKEN

- .github/workflows/update-readme-table.yaml
should fix https://github.com/googleapis/java-cloud-bom/actions/workflows/update-readme-table.yaml creating PRs in the wrong branch name.
> chore: fix branch name in workflow

- tests/validate-bom/src/main/java/com/google/cloud/CreateBomCanaryProject.java
> chore: exclude grpc-android from bom validation

- libraries-bom-table-generation/javaModulesMetadata.yaml
- tests/dependency-convergence/pom.xml
Error from the full-dependencies-check:
```
Error: ] Some problems were encountered while processing the POMs:
Error:  'dependencies.dependency.version' for com.google.cloud:google-cloud-game-servers:jar is missing. @ line 202, column 17
@ 
Error:  The build could not read 1 project -> [Help 1]
Error:    
Error:    The project com.google.cloud:full-convergence-check:0.25.0 (/home/runner/work/java-cloud-bom/java-cloud-bom/tests/dependency-convergence/pom.xml) has 1 error
Error:      'dependencies.dependency.version' for com.google.cloud:google-cloud-game-servers:jar is missing. @ line 202, column [17](https://github.com/googleapis/java-cloud-bom/actions/runs/6645 …
```
> chore: Remove references to game-server module

- .kokoro/nightly/create-versions-csv.sh
fix kokoro job failing with error message:
```
+ bq load --autodetect --project_id=cloud-java-metrics --source_format=CSV client_library_versions.cloud_java_client_library_release_dates cloud_java_client_library_release_dates.csv
Upload complete.Waiting on bqjob_r28424c53fa9642fd_0000018b47445529_1 ... (0s) Current status: RUNNING                                                                                      Waiting on bqjob_r28424c53fa9642fd_0000018b47445529_1 ... (0s) Current status: DONE  
BigQuery error in load operation: Error processing job
'cloud-java-metrics:bqjob_r28424c53fa9642fd_0000018b47445529_1': Provided Schema
does not match Table cloud-java-metrics:client_library_versions.cloud_java_clien
t_library_release_dates. Cannot add fields (field: string_field_0)
Failure …
```
> fix: fix pipeline failure due to bigquery Provided Schema does not match Table.

- .kokoro/nightly/create-versions-csv.sh
This change should fix the issue that all these 4 artifacts are mapped to service "bigstore".
```
google-cloud-bigquerystorage 
google-cloud-storage
google-cloud-storage-transfer
google-cloud-storageinsights # I was not able to find corresponding log items
```
> fix: specify artifact_id to replace explicitly.

- .kokoro/nightly/create-versions-csv.sh
These preview modules need to be tracked too. They have different versions (e.g. [4.7.2-preview](https://repo1.maven.org/maven2/com/google/cloud/google-cloud-language-spring-starter/4.7.2-preview/)) than spring-cloud-gcp.
Because there is no module that is unique to and all preview module depend on, use `google-cloud-language-spring-starter` to track versions. (this module is also used in spring-generator manual tests)
> fix(libraries-release-data): add spring autogen to tracked libraries.

- dashboard/pom.xml
Reverts googleapis/java-cloud-bom#6671
This is a major version bump and cause the dashboard ci failed:
```
Error:  Failed to execute goal org.codehaus.mojo:exec-maven-plugin:3.0.0:java (default-cli) on project google-cloud-bom-dashboard: An exception occured while executing the Java class. org.codehaus.plexus.component.repository.exception.ComponentLookupException: com.google.inject.ProvisionException: Unable to provision, see the following errors:
Error:  
Error:  1) null returned by binding at org.eclipse.sisu.wire.LocatorWiring
Error:   but the 7th parameter of org.eclipse.aether.internal.impl.DefaultRepositorySystem.<init>(Unknown Source) is not @Nullable
Error:    at org.eclipse.sisu.wire.LocatorWiring
Error:    while locating org.eclipse.aether.impl.Installer
Error:      for the 7th …
```
> Revert "build(deps): update dependency org.apache.maven.resolver:maven-resolver-api to v2"

- README.md
Link to Google Cloud Shared Dependencies points to archived repo. Update to maintained project.
> chore: update link to Google Cloud Shared Dependencies

- libraries-bom-protobuf3/pom.xml
- libraries-bom/pom.xml
- release-note-generation/src/main/java/com/google/cloud/ReleaseNoteGeneration.java
- renovate.json
- versions.txt
In this PR:
- Add a new `protobuf-bom` section to `libraries-bom` to override the protobuf runtime version to the latest.
- Add a new generated release notes to direct customers to use `libraries-bom-protobuf3` if there is any incompatibility issues.
- Update the version of `libraries-bom-protobuf3` to match the version of `libraries-bom`.
- Disables `protobuf-bom` from being updated by renovate bot.
> chore: Override the version of protobuf-bom to 4.28.3 in libraries-bom.

- README.md
Starting [libraries-bom v26.50.0](https://github.com/googleapis/java-cloud-bom/releases/tag/v26.50.0), we release two boms: libraries-bom that includes protobuf-java runtime 4.x, and libraries-bom-protobuf3 that includes protobuf-java runtime 3.x. libraries-bom is still the preferred solution, libraries-bom-protobuf3 is a backup solution only for customers that have conflicts with protobuf-java runtime 3.x.
See [go/cloud-sdk-java-protobuf-upgrade-strategy-design](https://goto.google.com/cloud-sdk-java-protobuf-upgrade-strategy-design) for details.
> chore: Add documentation for libraries-bom-protobuf3 to README

- google-cloud-bom/pom.xml
- libraries-bom/pom.xml
Tested externally using:
[linkage checker](https://github.com/lqiu96/gapic-generator-java/actions/runs/12772035369)
[protobuf nightly check](https://github.com/googleapis/sdk-platform-java/actions/runs/12770706829)
[manual linkage checker for mono repo](https://paste.googleplex.com/4563607153803264)
> deps: update protobuf to 4.29.0

- .github/workflows/release-note-generation.yaml
Similar to https://github.com/googleapis/google-cloud-java/pull/11503
> ci: grant permissions to release note generation workflow

- .github/workflows/update-readme-table.yaml
The workflow has been failing due to organization-wide permission change. https://github.com/googleapis/java-cloud-bom/actions/workflows/update-readme-table.yaml:
> ci: grant permission to update-readme workflow

- google-cloud-bom/pom.xml
- libraries-bom/pom.xml
As the preparation for Central Portal API publication, we need to wrap nexus-staging-maven-plugin with a profile.
The profile matches java-shared-config.
https://github.com/googleapis/java-shared-config/blob/main/native-image-shared-config/pom.xml#L112
b/422134662
> ci: wrap nexus-staging-maven-plugin with a profile

- libraries-bom-protobuf3/pom.xml
update protobuf version for libraries-bom-protobuf3. 
Merge when upstream changes are in.
> deps: Upgrade Protobuf-Java to v3.25.8
