googleapis/java-cloud-bom

.kokoro/bom-upper-bounds-check.sh
.kokoro/presubmit/bom-upper-bounds.cfg

This test is migrated from https://github.com/googleapis/google-cloud-java

test: add BOM Upper Bounds test

---

pom.xml

deps: import video-intelligence bom and update to 0.116.0

---

pom.xml

deps: import bigtable bom and update to 1.7.1

---

pom.xml

deps: import kms bom and update to 1.35.0

---

pom.xml

deps: import language bom and update to 1.99.0

---

pom.xml

deps: import logging bom and update to 1.99.0

---

pom.xml

deps: import recaptchaenterprise bom and update to 0.28.0

---

pom.xml

deps: import securitycenter bom

---

pom.xml

deps: import os-login bom and update to 0.117.0

---

pom.xml

deps: import monitoring bom and update to 1.99.0

---

pom.xml

deps: import redis bom and update to 0.117.0-alpha

---

pom.xml

deps: import pubsub bom and update to 1.102.0

---

pom.xml

deps: import scheduler bom and update to 1.22.0

---

pom.xml

deps: import dialogflow bom and update to 0.118.0-alpha

---

pom.xml

deps: import firestore bom and update to 1.32.0

---

pom.xml

deps: import error-reporting bom and update to 0.118.0-beta

---

pom.xml

deps: import webrisk bom and update to 0.31.0-alpha

---

pom.xml

deps: import dataproc bom and update to 0.118.0

---

pom.xml

deps: import container bom and update to 0.118.0-beta

---

pom.xml

deps: import containeranalysis bom and update to 0.118.0-beta

---

pom.xml

feat(deps): import build bom

---

pom.xml

feat(deps): import google-cloud-recommender bom

---

pom.xml

feat(deps): import billingbudgets bom

---

pom.xml

google-cloud-automl-bom 0.115.1

---

pom.xml

chore(deps): update GAX and core

---

pom.xml

chore: alphabetize imports

---

pom.xml

feat: import bigquerystorage-bom instead of individual artifacts

---

pom.xml

feat: import google-cloud-bigquerydatatransfer-bom, update to 0.121.0-beta

---

pom.xml

feat: import google-cloud-spanner-bom, update to 1.49.0

---

pom.xml

Fixes #11 
This makes updating after a release of datastore easier

feat: import google-cloud-datastore-bom

---

pom.xml

build: specify com.coveo google-format version

---

README.md

docs: adverbs are weak; omit needless words

---

synth.py

Manages changes brought in from #845

chore: exclude samples lint checks

---

pom.xml

These dependencies are managed in google-cloud-shared-dependencies BOM
cc @elharo @suztomo

feat!: remove common dependencies from google-cloud-bom

---

pom.xml

feat: add google-cloud-os-config API

---

pom.xml

feat: add google-cloud-functions

---

pom.xml

feat: add google-cloud-game-servers API

---

dashboard/src/main/java/com/google/cloud/tools/opensource/cloudbomdashboard/ArtifactMavenData.java

Fixes https://github.com/googleapis/java-bigquery/issues/881

fix: version from properties

---

dashboard/src/main/java/com/google/cloud/tools/opensource/cloudbomdashboard/ArtifactMavenData.java

fix: version from release

---

dashboard/README.md
dashboard/pom.xml
dashboard/src/main/java/com/google/cloud/tools/opensource/cloudbomdashboard/ArtifactCache.java
dashboard/src/main/java/com/google/cloud/tools/opensource/cloudbomdashboard/ArtifactInfo.java
dashboard/src/main/java/com/google/cloud/tools/opensource/cloudbomdashboard/ArtifactMavenData.java
dashboard/src/main/java/com/google/cloud/tools/opensource/cloudbomdashboard/ArtifactResults.java
dashboard/src/main/java/com/google/cloud/tools/opensource/cloudbomdashboard/DashboardArguments.java
dashboard/src/main/java/com/google/cloud/tools/opensource/cloudbomdashboard/DashboardMain.java
dashboard/src/main/java/com/google/cloud/tools/opensource/cloudbomdashboard/VersionData.java

This is an option so that you don't need to build the entire dashboard and open the webpage.
Towards #735

dashboard: add option to print report to stdout

---

.kokoro/bom-upper-bounds-check.sh

@chingor13 @suztomo
Thank you for openin

fix: omit download progress from build logs

---

dashboard/pom.xml

chore: clean up dashboard dependencies

---

pom.xml

Added Google Channel Services, Google Cloud Retail and Google Cloud Organization Policy

feat: update google cloud bom with new GA libraries

---

dependency-convergence/pom.xml

chore: fix dependencies

---

.github/workflows/ci.yaml
.github/workflows/dashboard.yaml
.github/workflows/full-convergence-check.yaml

chore: configure initial java7 version

---

pom.xml

feat: add google-cloud-eventarc
feat: add google-cloud-filestore
feat: add google-cloud-network-management
feat: add google-cloud-resource-settings
feat: add google-cloud-service-control

feat: add google-cloud-debugger-client

---

.github/release-please.yml

Towards https://github.com/googleapis/releasetool/issues/361

chore: use release-please to tag releases

---

pom.xml

For https://github.com/googleapis/java-pubsublite/issues/927 ☕️
CC: @dpcollins-google @Neenu1995 
```
suztomo@suztomo2:~/java-cloud-bom$ mvn help:effective-pom -Dverbose
...
<dependency>
<groupId>com.google.cloud</groupId>  
<artifactId>google-cloud-pubsublite</artifactId>  
<version>1.4.0</version>  
</dependency>
<dependency>
<groupId>com.google.api.grpc</groupId>  
<artifactId>grpc-google-cloud-pubsublite-v1</artifactId>  
<version>1.4.0</version>  
</dependency>
<dependency>
<groupId>com.google.api.grpc</groupId>  
<artifactId>proto-google-cloud-pubsublite-v1</artifactId>  
<version>1.4.0</version>  
</dependency>
```

feat: adding Google Cloud Pubsublite BOM

---

pom.xml

deps: update dependency com.google.cloud:google-cloud-dlp:3.1.1
deps: update dependency com.google.cloud:google-cloud-secretmanager:2.0.7
deps: update dependency com.google.cloud:google-cloud-bigtable:2.5.1
deps: update dependency com.google.cloud:google-cloud-nio:0.123.18
deps: update dependency com.google.cloud:google-cloud-bigqueryreservation:2.2.1
deps: update dependency com.google.cloud:google-cloud-pubsublite:1.4.8
deps: update dependency com.google.cloud:google-cloud-workflows:2.1.5
deps: update dependency com.google.cloud:google-cloud-orchestration-airflow:1.1.1
deps: update dependency com.google.cloud:google-cloud-vpcaccess:2.1.5
deps: update dependency com.google.cloud:google-cloud-bigquerystorage:2.8.1
deps: update dependency com.google.cloud:google-cloud-translate:2.1.9
deps: …

deps: update dependency com.google.cloud:google-cloud-bigquery:2.6.1

---

pom.xml

chore(deps): grafeas 2.2.1 (shared-deps 2.7.0)

---

pom.xml

Reverts googleapis/java-cloud-bom#3619

deps: downgrade dependency org.sonatype.plugins:nexus-staging-maven-plugin to v1.6.8

---

tests/dependency-convergence/pom.xml

Follow-up of troubleshooting in https://github.com/googleapis/java-cloud-bom/pull/4301#issuecomment-1139899428

ci: test directory version upgrade

---

tests/dependency-convergence/pom.xml

It didn't work https://github.com/googleapis/java-cloud-bom/pull/4728#issuecomment-1204101268

ci: reverting the marker in tests

---

README.md
google-cloud-bom/README.md

README.md explaining users to use the Libraries BOM and the scope.
It's from Google Doc "Google Cloud Libraries BOM principle".
Fixes https://github.com/googleapis/java-cloud-bom/issues/1580

docs: explaining users to use the Libraries BOM

---

.release-please-manifest.json
release-please-config.json
tests/dependency-convergence/pom.xml
tests/dependency-convergence/versions.txt

Adding tests/dependency-converge in config so that release-please updates its pom.xml

chore: Adding "tests/dependency-convergence" module to release please config

---

.release-please-manifest.json
release-please-config.json
tests/dependency-convergence/pom.xml

chore: Removed tests from manifest config

chore: removing tests from manifest config

---

libraries-bom/pom.xml

Touching libraries-bom/pom.xml so that it appear in the release pull request https://github.com/googleapis/java-cloud-bom/pull/4963

fix: touching libraries-bom/pom.xml

---

.kokoro/release/stage.sh
.kokoro/requirements.txt
google-cloud-bom/pom.xml
owlbot.py
pom.xml

chore: removing unnecessary site configuration and added explanation on why it's setup like this.

chore: clarify nexus-staging-plugin setup

---

.kokoro/requirements.txt
libraries-bom/pom.xml

chore: Release as version 26.3.0

---

.github/workflows/ci.yaml
.github/workflows/dashboard.yaml
.github/workflows/full-convergence-check.yaml

ci: configure the protected branch

---

.github/workflows/release-note-generation.yaml

ci: install BOMs locally when creating release notes

---

.github/workflows/full-convergence-check.yaml
tests/src/test/java/com/google/cloud/BomContentTest.java

- ci: removing the experimental convergence check
- Added explanation in the test case

ci: remove the experimental full convergence check

---

google-cloud-bom/pom.xml
tests/src/test/java/com/google/cloud/BomContentTest.java

test: revert temporary fix for group IDs of analytics libraries

---

.github/workflows/ci-release-note-generation.yaml
.github/workflows/ci.yaml
.github/workflows/dashboard.yaml
.github/workflows/full-convergence-check.yaml
.github/workflows/release-note-generation.yaml
tests/validate-bom/README.md
tests/validate-bom/action.yml
tests/validate-bom/pom.xml
tests/validate-bom/src/main/java/com/google/cloud/CreateBomCanaryProject.java
tests/validate-bom/src/main/resources/template.pom.xml

Fixes #5922 
It worked in https://github.com/googleapis/gapic-generator-java/pull/1629
Todo: 
- Merge this pull request 5928.
- Update the branch name in https://github.com/googleapis/gapic-generator-java/pull/1629 to "main"
- Add another check in https://github.com/googleapis/google-cloud-java with "main"

ci: GitHub Actions to validate a Maven BOM

---

.github/workflows/ci-validate-bom.yaml
libraries-bom/pom.xml
tests/validate-bom/action.yml
tests/validate-bom/src/main/resources/template.pom.xml

Adding further check.  This also adds a test for validate-bom logic.
Fixes https://github.com/googleapis/java-cloud-bom/issues/5936.

test: BOM validation via dependency tree

---

tests/src/test/java/com/google/cloud/BomContentTest.java

chore: temporarily fix test to cater for maven cache issue

---

.github/sync-repo-settings.yaml

This is keep in compliance with: https://github.com/googleapis/synthtool/pull/1800

chore: Add dependencies(17) as the only required check

---

libraries-bom/pom.xml

fix: Use Guava v32.1.2 to resolve gradle metadata issue

---

libraries-bom/pom.xml

This reverts commit d4cf9697766e5ac11927bb1e10bf4d5c2a149f63.

Revert "fix: Use Guava v32.1.2 to resolve gradle metadata issue (#6140)"

---

CONTRIBUTING.md
owlbot.py

chore: updating contribution guideline

---

.github/workflows/approve-readme.yaml
.github/workflows/ci.yaml
.github/workflows/renovate_config_check.yaml
.repo-metadata.json

docs: update repo-metadata.json with cgc link

---

libraries-bom/pom.xml

Just a documentation comment update

chore(docs): update first-party-dependencies link

---

google-cloud-bom/pom.xml

BEGIN_COMMIT_OVERRIDE
deps: update dependency com.google.cloud:google-cloud-datastore-bom to v2.21.1
deps: update dependency com.google.cloud:google-cloud-firestore-bom to v3.24.3
deps: update dependency com.google.cloud:google-cloud-bigtable-bom to v2.42.0
deps: update dependency com.google.cloud:google-cloud-spanner-bom to v6.72.0
END_COMMIT_OVERRIDE

deps: Update Java client library dependencies

---

google-cloud-bom/pom.xml

BEGIN_COMMIT_OVERRIDE
deps: update dependency com.google.cloud:google-cloud-nio to v0.127.21
deps: update dependency com.google.cloud:google-cloud-spanner-jdbc to v2.20.2
END_COMMIT_OVERRIDE

deps: Update Google Cloud Client Library Dependencies

---

google-cloud-bom/pom.xml

deps: update dependency com.google.cloud:google-cloud-logging-logback to v0.131.17-alpha

---

google-cloud-bom/pom.xml

deps: update dependency com.google.cloud:google-cloud-pubsub-bom to v1.134.2

---

google-cloud-bom/pom.xml

deps: updated dependency of google-cloud-bigtable-bom

---

libraries-bom/pom.xml

deps: Protobuf 4.29.4 in Libraries BOM

---

.kokoro/nightly/get-service-names.sh

This script lacked error handling, causing it to fail when modules like [java-marketingplatformadminapi](https://github.com/googleapis/google-cloud-java/tree/main/java-marketingplatformadminapi)
See context in [doc](https://docs.google.com/document/d/1fh4paz0K_cVmk63nM3PSJj9MkQN8kWCQN2yqfEeF49U/edit?resourcekey=0-uAKnlOeiAnBkQ9Yf-ZCyWw&tab=t.0)
This fix is manually tested and can get a peek of data with 
```
SELECT * FROM `cloud-java-metrics.client_library_versions.cloud_java_client_library_release_dates` 
WHERE TIMESTAMP_TRUNC(_PARTITIONTIME, DAY) = TIMESTAMP("2025-03-27") LIMIT 1000
```
For longer term, consider adding tests and/or refactoring.

fix: add error handling to get-service-names.sh
